POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoic2FlZWRAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjY2NDgyMiwiZXhwIjoxNzU2NjY4NDIyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ZwVBE8EF8K2VIK-TX_7FPIYm1yjx2UE8UICLLnz6yT8

{
    "title": "New Post22",
    "postType": "post",
    "status": "draft",
    "slug": "new-post-22",
    "content": "This is the content of the new post.",
    "schema": "{\r\n \"@context\": \"https://schema.org\",\r\n \"@type\": \"BlogPosting\",\r\n \"headline\": \"New Post\",\r\n \"articleBody\": \"This is the content of the new post.\"\r\n}",
    "featuredImageUrl": "http://example.com/image.jpg",
    "publishedOn": "2025-08-20T11:45:30.123Z",
    // "tags": ["nestjs", "typescript"],
    "metaOptions": {
        "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
    },
    "tags":[1]
}