DELETE http://localhost:3000/uploads/file?path=test-image-1756838889783-bb2f4ed7-fb91-4171-814f-d946a5e9b0e5.jpeg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoic2FlZWRAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTY4Mzg4NTAsImV4cCI6MTc1Njg0MjQ1MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.7E0IgqkAmVrx8mjkKMuy-M8IBvj0eVF9drhDl5HNjBI