POST http://localhost:3000/uploads/file
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhZWVkQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2MDgzOTA1LCJleHAiOjE3NTYwODc1MDUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.myWMfdfxq8wImNGXCRdTEP-ycqFpKbNv9EvBgBR2YOY
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test-image.jpeg"
Content-Type: image/jpeg

< ./test-image.jpeg
------WebKitFormBoundary--