POST http:localhost:3000/users
Content-Type: application/json


{
    "firstName": "saeed",
    "lastName": "Pakp",
    "email": "saeed1@sds.comm",
    "password": "Pssword123"
}

POST http:localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhZWVkQGV4YW1wbGUuY29tIiwic3ViIjo2LCJpYXQiOjE3NTU3MzQ3MTAsImV4cCI6MTc1NTczODMxMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.BOdi6CjZco926ytGu7GrUgafgjrI9oibUDOsWifAgP4
{
    "users": [
        {
            "firstName": "Mark",
            "lastName": "Doe",
            "password": "Pssword123",
            "email": "mark@example.com"
        },
        {
            "firstName": "Jane",
            "lastName": "Doe",
            "password": "Pssword123",
            "email": "jane.doe@example.com"
        }   
    ]

}
