POST http:localhost:3000/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "password": "Pssword123"
}

POST http:localhost:3000/users/create-many
Content-Type: application/json

{
    "users": [
        {
            "firstName": "Mark",
            "lastName": "Doe",
            "password": "Pssword123",
            "email": "mark@example.com"
        },
        {
            "firstName": "Jane",
            "lastName": "Doe",
            "password": "Pssword123",
            "email": "jane.doe@example.com"
        }   
    ]

}
